#!/usr/bin/perl -w

#  Call after 'Stopprp'
#  Tars entire PRP folder and stores in /home/rmr/prpdata/ folder
#  
#  Call:  perl ArchivePrp
#  
#  Output: $HomePath/prpdata/prparchive_20151020T123456Z.tar.gz
# 

use lib $ENV{MYLIB};
use perltools::MRutilities;
use perltools::MRtime;

	## DATA PATH
my $datapath="$ENV{HomePath}/swmain/apps/PRP";
#print"data path = $datapath\n";

	## ARCHIVE PATH
my $archivepath="$ENV{HomePath}/prpdata";
#print"Archive path=$archivepath\n";
if(! -d $archivepath){
	#print"Create $archivepath\n";
	`mkdir $archivepath`;
}

	## TAR FILE NAME
my $tarname=sprintf "prparchive_%s.tar.gz",dtstr(now(),'iso');
print"ArchivePrp $tarname\n";


	## TAR COMMAND
my $cmd = sprintf "cd $datapath; tar -zcf $archivepath/$tarname .";
#print"$cmd\n";
system $cmd;

exit 0;
