#! /usr/bin/perl -w

$usr=`whoami`;
chomp($usr);

	#=================
	# REMOVE ZOMBIES
	#=================
@removelist=("kermit","expect","perl");
foreach $xx (@removelist){
	$cmd="ps -u $usr -o pid,command | grep $xx";
	#print"test0 cmd = $cmd\n";
	@pslist = `$cmd`;
	#$ii=0; foreach(@pslist){chomp($_); print"test1 $ii, $pslist[$ii]\n"; $ii++} 
	foreach $pscmd (@pslist){
		if($pscmd =~ /$xx/){
			if( $pscmd !~ /Cleanupfrsr/){
				chomp($pscmd);
				$pscmd =~ s/^\s+//;
				#print"test2 $pscmd\n";
				@d=split/[ \t]+/,$pscmd;
# 				#$ii=0; foreach(@d){print"$ii, $d[$ii]\n"; $ii++} 
				$cmd="kill -9 $d[0] 2>/dev/null";
				print"$pscmd -- $cmd\n";
				`kill -9 $d[0] 2>/dev/null`;
			}
		}
	}
}
exit;

