#!/usr/bin/perl -w
# 2015-05-30,1121

use lib $ENV{MYLIB};
use perltools::MRtime;
use perltools::MRutilities;

my @f = ('prpraw');
my @v = ();
my ($f,$is,@s,$s,$cmd,$nw,$age);

$nw=now();
	# SELECT STREAM
for($is=0; $is<=$#f; $is++){
	$f=$f[$is];
	printf "$f  %d  ",$nw;
		# LAST RECORD TIME
	$cmd = sprintf("LastDataTime %s",$f);
	$s = `$cmd`;
	chomp($s); 
		# 1502064482 2017 8 6 17 8 2
	@s = split /[ ]+/, $s;
	if($#s<=0){
		print"bad -- record failure.\n";
		push @v,0;
	} else {
		$dt=$s[0];
		printf"%s  %d  ",dtstr($dt,'short'),$dt;
			# THE AGE OF THE RECORD
		if($dt==0){
			print"    0 -- RECORD FAILURE.\n",$f;
			push @v,0;		
		} else {
			$age = $nw - $dt;
			print"    $age";
			if ($age > 600){ print"    FAIL\n"; push @v,0}
			else{ print"    OK\n"; push @v, 1;  }
		}
	}
}
my $good=1;
foreach(@v){if($_ == 0){$good=0}}
print"good = $good\n";
`echo $good > /tmp/tmpdaq`;
exit 0
