#!/bin/bash
# This is called by bashrc hence at boottime

if [ -e ~/tmp/daqstart ]
then
        # daq was running at reboot.
    echo `date -u "+%y%m%d,%H%M%Sz"`--Backup data and re-start DAQ >> $HOME/tmp/bootlog
    
        # STOP
    crontab -r 2>/dev/null
    $DAQSWFOLDER/KillScreen >> $HOME/tmp/bootlog
    $DAQSWFOLDER/ArchivePrp >> $HOME/tmp/bootlog
    $DAQSWFOLDER/ClearPrpData y >> $HOME/tmp/bootlog
        # START
    $DAQSWFOLDER/PrepareForRun >> $HOME/tmp/bootlog
    echo SCREEN create >> $HOME/tmp/bootlog
    screen -S PRP -d -m -c $DAQSWFOLDER/tools/screenrc_prp.txt
        # START PROCESSES
    echo CRONTAB create >> $HOME/tmp/bootlog
    crontab $DAQSWFOLDER/tools/crontab_prp.txt  2>/dev/null
    echo BEGIN DAQ >> $HOME/tmp/bootlog
	screen -S PRP -d -m -c $DAQSWFOLDER/tools/screenrc_prp.txt
    screen -S PRP -p 1 -X stuff "G$(printf \\r)"
else
	echo `date -u "+%y%m%d,%H%M%Sz"`--REBOOT. No DAQ. >> $HOME/tmp/bootlog
fi


Start () {
	ps cax | grep Z_prp > /dev/null   # Z_prp is the app in question		
	if [ $? -eq 0 ]; then
		echo "DAQ is already running."
	else 
		touch ~/tmp/daqstart;
		KillScreen > /dev/null 2>&1;
		cd $DAQSWFOLDER;
		PrepareForRun > /dev/null;
		export RUNSETUPFILE=`cat tmp`;
		crontab $DAQSWFOLDER/tools/crontab_prp.txt
		screen -S PRP -d -m -c $DAQSWFOLDER/tools/screenrc_prp.txt
		screen -S PRP -p 1 -X stuff "G$(printf \\r)"
		isscreen
	fi
}
