#!/usr/bin/perl

$str=`screen -S PRP -ls`;
chomp($str);
@w=split /\t/,$str;

#foreach(@w){print"$_\n"}
#print"w[1] = $w[1]\n";

$l=length($w[1]);
if ($l <=0) {
	print"No screens with the name PRP.\n";
	exit 0
}
else {
	@d=split /\./,$w[1];
	print"KILL Screen $d[0]\n";
	`kill $d[0]`;
}

exit 0
