#!/usr/bin/perl -w
# call
#	LastDataFolder -- if a data folder exists
#		/Users/rmr/swmain/apps/PRP/data/data_20150804T005357Z
#	LastDataFolder -- if a data folder does NOT exist
#		0
#	LastDataFolder prp_raw -- if a data folder and time series folder exists
#		/Users/rmr/swmain/apps/PRP/data/data_20150804T005357Z/prp_raw_20150804.txt
#	LastDataFolder prp_raw -- if a data folder or time series folder do NOT exist
#		0

my @x = `ls -d $ENV{DAQFOLDER}/data/data* 2>/dev/null`;
if ($#x <0){print"0"; exit 1}

my $s;
chomp($s=$x[$#x]);

if($#ARGV<0){print"$s";}
else {
	my $a = shift();
	my @rw = `ls -1 $s/$a*.txt 2>/dev/null`;
	#foreach(@rw){chomp($_); print"test LDF $_\n"}
	if ($#rw < 0 ){print'0'; exit 1}
	else {
		chomp($fz=$rw[$#rw]); 
		$fz =~ s/^\s+//;
		print"$fz";
	}
}
exit 0;
