#!/usr/bin/perl -X


	## RUN FROM THE DAQ sw folder
	# PERLTOOL IN THE ~/sw/perl FOLDER
use lib "$ENV{DAQLIB}";
use perltools::MRtime;

		#=========================
		# MAKE SURE THE CORRECT FOLDERS ARE IN PLACE
		# IF NOT, THEN CREATE THEM
		#========================
		# DATA FOLDER
$fndata0 = "$ENV{DAQDATAFOLDER}";
if ( ! -d $fndata0 ) {
	print"DATA FOLDER IS MISSING, STOP\n";
	exit 1;
}
print"MAIN DATA FOLDER: $fndata0\n";

		#========================
		# CREATE THE NEW DATA FOLDER FOR THIS RUN
		#========================
my $dt0 = now();
$fndata = sprintf "$fndata0/data_%s", dtstr($dt0,'iso');
`mkdir $fndata`;
print"RUN DATA FOLDER = $fndata\n";

		#========================
		# MOVE THE SETUP FILE INTO THIS FOLDER
		#========================
print"CURRENT SETUP FILE = $ENV{SETUPFILE}\n";
$fsu = sprintf "%s/su_%s.txt", $fndata, dtstr($dt0,'iso');
#print"RUN SETUP FILE =     $fsu\n";
`cp $ENV{SETUPFILE} $fsu`;

		#========================
		# MODIFY THE SETUP FILE 
		#  THIS FILE = $fsu
		#perl -pi -e 's/: (.+)/: Mikes test/g if /^EXPERIMENT NAME/' tmp
		#========================
		# HEADER LINE
$cmd=sprintf "perl -pi -e 's!: (.+)!: %s!g if /^THIS FILE/' %s", $fsu, $fsu;
#print"\ncmd = $cmd\n";
system $cmd;
		# OUT PATH
$cmd=sprintf "perl -pi -e 's!: (.+)!: %s!g if /^RT OUT PATH/' %s", $fndata, $fsu;
#print"\ncmd = $cmd\n";
system $cmd;


		#========================
		# setupfile -> tmp
		#========================
open(F,'>tmp'); print F "$fsu\n"; close F;

print"-->> SETUPFILE =     $fsu\n";

exit

