#! /usr/bin/perl
# edit 20170727T195309Z

use lib $ENV{MYLIB};
use perltools::MRtime;
#use Device::SerialPort qw( :PARAM :STAT 0.07 );

$fin="simulate/prpraw_180611.txt";

my $irec = 0;
my ($i1,$narg,$p);

$narg = $#ARGV;
if($narg>=0){
	foreach(@ARGV){print"  $_\n"}
}

while (1) {
	$irec = 0;
	open(F,"<$fin") or die("fin error\n");

	# Loop through all the data records.
	while (<F>) {
		chomp( $str = $_);
		if($str =~ /##/){
			print"$str\r\n";
			sleep(5);
			$irec++;
		}
	}
	print"Starting over\n";
	close F;
}
