#!/bin/bash

# crontab -e to set this cron job
#To use my bashrc stuff
#MAILTO=""
#BASH_ENV="$HOME/.bashrc"
#SHELL=/bin/bash
#    SBD transmit
#26,56 * * * * $DAQSWFOLDER/sbd_transmit >> $DAQDATAFOLDER/sbdlog
#    Check and reboot
#14 * * * * $DAQSWFOLDER/UpdateDaq >> $DAQDATAFOLDER/daqlog
			
version="UpdateDaq v2 180404"
cd $DAQSWFOLDER

echo $version" ====================" >> $DAQDATAFOLDER/daqlog;
date -u "+%Y %m %d %H %M %S Z" >> $DAQDATAFOLDER/daqlog;

DaqUpdate >> $DAQDATAFOLDER/daqlog

chk=`cat /tmp/tmpdaq`;
if [ $chk -eq 1 ] > /dev/null ; then
	echo OK
	echo "UpdateDaq, no reboot." >> $DAQDATAFOLDER/daqlog
	exit 0;
fi

if [ $chk -eq 0 ] > /dev/null ; then
	echo REBOOT
	echo "REBOOT." >> $DAQDATAFOLDER/daqlog
		# STOPPRP
 	$DAQSWFOLDER/KillScreen >> $DAQDATAFOLDER/daqlog
 	$DAQSWFOLDER/Cleanupprp >> $DAQDATAFOLDER/daqlog
		# STARTPRP
	$DAQSWFOLDER/PrepareForRun >> $DAQDATAFOLDER/daqlog
	screen -S PRP -d -m -c $DAQSWFOLDER/tools/screenrc_prp.txt
		# START PROCESSES
	screen -S PRP -p 1 -X stuff "bash$(printf \\r)"
	screen -S PRP -p 1 -X stuff "G$(printf \\r)"

	#echo UpdateDaq, reboot exit >> $DAQDATAFOLDER/daqlog
	exit 0;
fi
exit 0;

